name: Release Binary Package
on:
  push:
    tags:
      - v*

jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the sources"
        uses: actions/checkout@v2.3.1
      - name: Install JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v1
      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: "/home/runner/.cache/bazel"
          key: caches-${{ runner.os }}-release
      - name: Build release artifact
        run: bazelisk build //:work_request_handlers_deploy.jar
      - name: Create release sha256
        run: shasum -a 256 bazel-bin/work_request_handlers_deploy.jar > work_request_handlers.jar.sha256
      - name: Upload bazel-bin/bazel-bin/work_request_handlers.jar
        uses: svenstaro/upload-release-action@2.7.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bazel-bin/work_request_handlers_deploy.jar
          asset_name: work_request_handlers.jar
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload bazel-bin/work_request_handlers.jar.sha256
        uses: svenstaro/upload-release-action@2.7.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: work_request_handlers.jar.sha256
          asset_name: work_request_handlers.jar.sha256
          tag: ${{ github.ref }}
          overwrite: true
